[versions]
commons-cli = "1.9.0"
commons-math3 = "3.6.1"
guava = "33.4.8-jre"
junit = "4.13.2"
jaxb4_api = "4.0.5"
jaxb = "4.0.8"
xjc = "4.0.8"
slf4j = "2.0.17"

[libraries]
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commons-cli" }
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }
jaxb4-api = {group = "jakarta.xml.bind", name = "jakarta.xml.bind-api", version.ref = "jaxb4_api"}
jaxb4-xjc = {group = "org.glassfish.jaxb", name = "jaxb-xjc", version.ref = "xjc"}
jaxb4-runtime = {group = "org.glassfish.jaxb", name = "jaxb-runtime", version.ref = "jaxb"}
slf4j-api = {group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j"}
slf4j-jcl =  {group = "org.slf4j", name = "jcl-over-slf4j", version.ref = "slf4j"}
slf4j-simple =  {group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j"}

[plugins]
spotbugs = {id = "com.github.spotbugs", version = "6.0.18"}
nexus-publish = {id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0"}
